service: unofficial-mbmbam-episode-api

provider:
  name: aws
  region: us-east-1
  runtime: nodejs8.10

package:
  include:
    - node_modules/**

functions:
  getEpisodes:
    handler: handler.getEpisodes
    description: Return object containing channel info and paginated episode list. Accepts `search`, `number`, `page` url queries.
    memorySize: 256
    events:
      - http:
          path: /episodes
          method: get
    environment:
      RSS_URL: http://feeds.feedburner.com/mbmbam?format=xml
      RESULTS_PER_PAGE: 10

  getLatestEpisode:
    handler: handler.getLatestEpisode
    description: Return object containing channel info and latest episode.
    memorySize: 256
    events:
      - http:
          path: /episodes/latest
          method: get
    environment:
      RSS_URL: http://feeds.feedburner.com/mbmbam?format=xml
      RESULTS_PER_PAGE: 10

  warmCache:
    handler: handler.warmCache
    memorySize: 256
    events:
      - schedule:
          description: cache warmer for the unofficial mbmbam rss api
          rate: rate(5 minutes)
          enabled: true
    environment:
      RSS_URL: http://feeds.feedburner.com/mbmbam?format=xml
